### ISSUE TITLE
Seems to be broken on Linux

### ISSUE THREAD

**Issue by toji** [montagejs/mop#17]
Attempting to build a project on an Ubuntu machine with Mop (0.12.3, installed via npm with -g) is consistently giving me the following error:

```
Error: Can't find package.json in "file:///path/to/project/"
    at reconfigurePackage (/usr/local/lib/node_modules/mop/lib/reconfigure.js:37:15)
    at /usr/local/lib/node_modules/mop/node_modules/collections/shim-object.js:255:18
    at Array.forEach (native)
    at Function.forEach (/usr/local/lib/node_modules/mop/node_modules/collections/shim-object.js:254:25)
    at reconfigure (/usr/local/lib/node_modules/mop/lib/reconfigure.js:7:12)
    at /usr/local/lib/node_modules/mop/lib/build.js:27:20
    at /usr/local/lib/node_modules/mop/node_modules/q/q.js:860:30
From previous event:
    at build (/usr/local/lib/node_modules/mop/lib/build.js:20:6)
    at optimize (/usr/local/lib/node_modules/mop/optimize.js:54:12)
    at main (/usr/local/lib/node_modules/mop/optimize.js:145:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/mop/optimize.js:158:5)
```

I've verified that there is indeed a package.json at the path in question, and the same code builds as expected on OSX.

(BTW: Love the little spinny animation while it builds!)

**Comment by cdebost** [comment]
Considering the number of mop and ubuntu versions that have been released since this issue was opened, I'd say this is safe to close.
